### ISSUE TITLE
Undefined Errors

### ISSUE THREAD

**Issue by bdunn44** [bdunn44/MEJS-Vaadin#5]
When in debug mode the javascript console displays errors indicating a Javascript bug. In Vaadin 7.4+ this apparently causes the UI to load multiple times.

```
Firefox:

33508ms(TypeError) __gwt$exception: : p is undefinedcom.google.gwt.core.client.JavaScriptException: (TypeError) __gwt$exception: : p is undefined
at Unknown.com_kbdunn_vaadin_addons_mediaelement_MediaElementPlayer/t.updateSource(Unknown Source)
at Unknown.JRb(Unknown Source)
at Unknown.zRb(Unknown Source)
at Unknown.NRb(Unknown Source)
at Unknown.o0b(Unknown Source)
at Unknown.FOb(Unknown Source)
at Unknown.EOb(Unknown Source)
at Unknown.ROb(Unknown Source)
at Unknown.bMb(Unknown Source)
at Unknown.PNb(Unknown Source)
at Unknown.SNb(Unknown Source)
at Unknown.ZTb(Unknown Source)
at Unknown.nUb(Unknown Source)
at Unknown.dUb/a.onload<(Unknown Source)
at Unknown.ro(Unknown Source)
at Unknown.wo(Unknown Source)
at Unknown.vo/<(Unknown Source)
at Unknown.anonymous(Unknown Source)

and (in Chrome):

12969ms (TypeError) __gwt$exception: : Cannot read property 'setSource' of undefinedcom.google.gwt.core.client.JavaScriptException: (TypeError) __gwt$exception: : Cannot read property 'setSource' of undefined
at Unknown.t.updateSource(http://localhost:8080/AISVOPAC/VAADIN/addons/mejs-player/mejs-player-connector.js@4)
at Unknown.JRb(nz.co.ais.mtvic.gwt.Mywidgetset-2.js@26)
at Unknown.zRb(nz.co.ais.mtvic.gwt.Mywidgetset-2.js@155)
at Unknown.NRb(nz.co.ais.mtvic.gwt.Mywidgetset-2.js@41806)
at Unknown.o0b(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@178)
at Unknown.FOb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@204)
at Unknown.EOb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@515)
at Unknown.ROb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@12800)
at Unknown.bMb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@106)
at Unknown.PNb(nz.co.ais.mtvic.gwt.Mywidgetset-0.js@179)
```

**Comment by bdunn44** [comment]
Closing this as the issue isn't being observed in the current release
