### ISSUE TITLE
Unable to set source when component isn't attached

### ISSUE THREAD

**Issue by bdunn44** [bdunn44/MEJS-Vaadin#7]
Creating this issue which was submitted in the Vaadin forum. If the `MediaElementPlayer` component is not attached to a UI when `#setSource()` is called for a `ConnectorResource` the following NPE is thrown:

``` java
java.lang.NullPointerException
    at com.vaadin.server.ResourceReference.getURL(ResourceReference.java:48)
    at com.kbdunn.vaadin.addons.mediaelement.MediaElementPlayer.createMediaResource(MediaElementPlayer.java:219)
    at com.kbdunn.vaadin.addons.mediaelement.MediaElementPlayer.setSource(MediaElementPlayer.java:212)
    at com.monitec.mapatiempos.main.gui.MediaPlayer.setSource(MediaPlayer.java:51)
```

**Comment by bdunn44** [comment]
Fixed with release 1.3.2 (fe4a73f).
